// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package org.gw.raft.rpc;

public interface GetValueRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.GetValueRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required bool readOnlySafe = 1;</code>
   * @return Whether the readOnlySafe field is set.
   */
  boolean hasReadOnlySafe();
  /**
   * <code>required bool readOnlySafe = 1;</code>
   * @return The readOnlySafe.
   */
  boolean getReadOnlySafe();
}
