// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package org.gw.raft.rpc;

/**
 * Protobuf type {@code raft.GetValueRequest}
 */
public final class GetValueRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.GetValueRequest)
    GetValueRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetValueRequest.newBuilder() to construct.
  private GetValueRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetValueRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new GetValueRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetValueRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            readOnlySafe_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gw.raft.rpc.CounterOutter.internal_static_raft_GetValueRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gw.raft.rpc.CounterOutter.internal_static_raft_GetValueRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gw.raft.rpc.GetValueRequest.class, org.gw.raft.rpc.GetValueRequest.Builder.class);
  }

  private int bitField0_;
  public static final int READONLYSAFE_FIELD_NUMBER = 1;
  private boolean readOnlySafe_;
  /**
   * <code>required bool readOnlySafe = 1;</code>
   * @return Whether the readOnlySafe field is set.
   */
  @java.lang.Override
  public boolean hasReadOnlySafe() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required bool readOnlySafe = 1;</code>
   * @return The readOnlySafe.
   */
  @java.lang.Override
  public boolean getReadOnlySafe() {
    return readOnlySafe_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasReadOnlySafe()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeBool(1, readOnlySafe_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(1, readOnlySafe_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gw.raft.rpc.GetValueRequest)) {
      return super.equals(obj);
    }
    org.gw.raft.rpc.GetValueRequest other = (org.gw.raft.rpc.GetValueRequest) obj;

    if (hasReadOnlySafe() != other.hasReadOnlySafe()) return false;
    if (hasReadOnlySafe()) {
      if (getReadOnlySafe()
          != other.getReadOnlySafe()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasReadOnlySafe()) {
      hash = (37 * hash) + READONLYSAFE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getReadOnlySafe());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gw.raft.rpc.GetValueRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.GetValueRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.GetValueRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gw.raft.rpc.GetValueRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code raft.GetValueRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.GetValueRequest)
      org.gw.raft.rpc.GetValueRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_GetValueRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_GetValueRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gw.raft.rpc.GetValueRequest.class, org.gw.raft.rpc.GetValueRequest.Builder.class);
    }

    // Construct using org.gw.raft.rpc.GetValueRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      readOnlySafe_ = false;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_GetValueRequest_descriptor;
    }

    @java.lang.Override
    public org.gw.raft.rpc.GetValueRequest getDefaultInstanceForType() {
      return org.gw.raft.rpc.GetValueRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.gw.raft.rpc.GetValueRequest build() {
      org.gw.raft.rpc.GetValueRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.gw.raft.rpc.GetValueRequest buildPartial() {
      org.gw.raft.rpc.GetValueRequest result = new org.gw.raft.rpc.GetValueRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.readOnlySafe_ = readOnlySafe_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gw.raft.rpc.GetValueRequest) {
        return mergeFrom((org.gw.raft.rpc.GetValueRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gw.raft.rpc.GetValueRequest other) {
      if (other == org.gw.raft.rpc.GetValueRequest.getDefaultInstance()) return this;
      if (other.hasReadOnlySafe()) {
        setReadOnlySafe(other.getReadOnlySafe());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasReadOnlySafe()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.gw.raft.rpc.GetValueRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.gw.raft.rpc.GetValueRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private boolean readOnlySafe_ ;
    /**
     * <code>required bool readOnlySafe = 1;</code>
     * @return Whether the readOnlySafe field is set.
     */
    @java.lang.Override
    public boolean hasReadOnlySafe() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required bool readOnlySafe = 1;</code>
     * @return The readOnlySafe.
     */
    @java.lang.Override
    public boolean getReadOnlySafe() {
      return readOnlySafe_;
    }
    /**
     * <code>required bool readOnlySafe = 1;</code>
     * @param value The readOnlySafe to set.
     * @return This builder for chaining.
     */
    public Builder setReadOnlySafe(boolean value) {
      bitField0_ |= 0x00000001;
      readOnlySafe_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required bool readOnlySafe = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearReadOnlySafe() {
      bitField0_ = (bitField0_ & ~0x00000001);
      readOnlySafe_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:raft.GetValueRequest)
  }

  // @@protoc_insertion_point(class_scope:raft.GetValueRequest)
  private static final org.gw.raft.rpc.GetValueRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gw.raft.rpc.GetValueRequest();
  }

  public static org.gw.raft.rpc.GetValueRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<GetValueRequest>
      PARSER = new com.google.protobuf.AbstractParser<GetValueRequest>() {
    @java.lang.Override
    public GetValueRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetValueRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetValueRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetValueRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.gw.raft.rpc.GetValueRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

