// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package org.gw.raft.rpc;

/**
 * Protobuf type {@code raft.IncrementAndGetRequest}
 */
public final class IncrementAndGetRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:raft.IncrementAndGetRequest)
    IncrementAndGetRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use IncrementAndGetRequest.newBuilder() to construct.
  private IncrementAndGetRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private IncrementAndGetRequest() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new IncrementAndGetRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private IncrementAndGetRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            bitField0_ |= 0x00000001;
            delta_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.gw.raft.rpc.CounterOutter.internal_static_raft_IncrementAndGetRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.gw.raft.rpc.CounterOutter.internal_static_raft_IncrementAndGetRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.gw.raft.rpc.IncrementAndGetRequest.class, org.gw.raft.rpc.IncrementAndGetRequest.Builder.class);
  }

  private int bitField0_;
  public static final int DELTA_FIELD_NUMBER = 1;
  private long delta_;
  /**
   * <code>required int64 delta = 1;</code>
   * @return Whether the delta field is set.
   */
  @java.lang.Override
  public boolean hasDelta() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>required int64 delta = 1;</code>
   * @return The delta.
   */
  @java.lang.Override
  public long getDelta() {
    return delta_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    if (!hasDelta()) {
      memoizedIsInitialized = 0;
      return false;
    }
    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeInt64(1, delta_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, delta_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.gw.raft.rpc.IncrementAndGetRequest)) {
      return super.equals(obj);
    }
    org.gw.raft.rpc.IncrementAndGetRequest other = (org.gw.raft.rpc.IncrementAndGetRequest) obj;

    if (hasDelta() != other.hasDelta()) return false;
    if (hasDelta()) {
      if (getDelta()
          != other.getDelta()) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasDelta()) {
      hash = (37 * hash) + DELTA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDelta());
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.gw.raft.rpc.IncrementAndGetRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.gw.raft.rpc.IncrementAndGetRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code raft.IncrementAndGetRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:raft.IncrementAndGetRequest)
      org.gw.raft.rpc.IncrementAndGetRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_IncrementAndGetRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_IncrementAndGetRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.gw.raft.rpc.IncrementAndGetRequest.class, org.gw.raft.rpc.IncrementAndGetRequest.Builder.class);
    }

    // Construct using org.gw.raft.rpc.IncrementAndGetRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      delta_ = 0L;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.gw.raft.rpc.CounterOutter.internal_static_raft_IncrementAndGetRequest_descriptor;
    }

    @java.lang.Override
    public org.gw.raft.rpc.IncrementAndGetRequest getDefaultInstanceForType() {
      return org.gw.raft.rpc.IncrementAndGetRequest.getDefaultInstance();
    }

    @java.lang.Override
    public org.gw.raft.rpc.IncrementAndGetRequest build() {
      org.gw.raft.rpc.IncrementAndGetRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public org.gw.raft.rpc.IncrementAndGetRequest buildPartial() {
      org.gw.raft.rpc.IncrementAndGetRequest result = new org.gw.raft.rpc.IncrementAndGetRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.delta_ = delta_;
        to_bitField0_ |= 0x00000001;
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.gw.raft.rpc.IncrementAndGetRequest) {
        return mergeFrom((org.gw.raft.rpc.IncrementAndGetRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.gw.raft.rpc.IncrementAndGetRequest other) {
      if (other == org.gw.raft.rpc.IncrementAndGetRequest.getDefaultInstance()) return this;
      if (other.hasDelta()) {
        setDelta(other.getDelta());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      if (!hasDelta()) {
        return false;
      }
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.gw.raft.rpc.IncrementAndGetRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.gw.raft.rpc.IncrementAndGetRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long delta_ ;
    /**
     * <code>required int64 delta = 1;</code>
     * @return Whether the delta field is set.
     */
    @java.lang.Override
    public boolean hasDelta() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int64 delta = 1;</code>
     * @return The delta.
     */
    @java.lang.Override
    public long getDelta() {
      return delta_;
    }
    /**
     * <code>required int64 delta = 1;</code>
     * @param value The delta to set.
     * @return This builder for chaining.
     */
    public Builder setDelta(long value) {
      bitField0_ |= 0x00000001;
      delta_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>required int64 delta = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearDelta() {
      bitField0_ = (bitField0_ & ~0x00000001);
      delta_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:raft.IncrementAndGetRequest)
  }

  // @@protoc_insertion_point(class_scope:raft.IncrementAndGetRequest)
  private static final org.gw.raft.rpc.IncrementAndGetRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.gw.raft.rpc.IncrementAndGetRequest();
  }

  public static org.gw.raft.rpc.IncrementAndGetRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  @java.lang.Deprecated public static final com.google.protobuf.Parser<IncrementAndGetRequest>
      PARSER = new com.google.protobuf.AbstractParser<IncrementAndGetRequest>() {
    @java.lang.Override
    public IncrementAndGetRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new IncrementAndGetRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<IncrementAndGetRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<IncrementAndGetRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public org.gw.raft.rpc.IncrementAndGetRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

