// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: counter.proto

package org.gw.raft.rpc;

public interface ValueResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:raft.ValueResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>required int64 value = 1;</code>
   * @return Whether the value field is set.
   */
  boolean hasValue();
  /**
   * <code>required int64 value = 1;</code>
   * @return The value.
   */
  long getValue();

  /**
   * <code>required bool success = 2;</code>
   * @return Whether the success field is set.
   */
  boolean hasSuccess();
  /**
   * <code>required bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>optional string redirect = 3;</code>
   * @return Whether the redirect field is set.
   */
  boolean hasRedirect();
  /**
   * <code>optional string redirect = 3;</code>
   * @return The redirect.
   */
  java.lang.String getRedirect();
  /**
   * <code>optional string redirect = 3;</code>
   * @return The bytes for redirect.
   */
  com.google.protobuf.ByteString
      getRedirectBytes();

  /**
   * <code>optional string errorMsg = 4;</code>
   * @return Whether the errorMsg field is set.
   */
  boolean hasErrorMsg();
  /**
   * <code>optional string errorMsg = 4;</code>
   * @return The errorMsg.
   */
  java.lang.String getErrorMsg();
  /**
   * <code>optional string errorMsg = 4;</code>
   * @return The bytes for errorMsg.
   */
  com.google.protobuf.ByteString
      getErrorMsgBytes();
}
